### ISSUE TITLE
Gitorious is going away

### ISSUE THREAD

**Issue by davidw** [ErlyORM/boss_db#214]
The uuid code should point at github instead of gitorious in rebar.config.  Same commit.

**Comment by danikp** [comment]
this one ?
https://github.com/avtobiff/erlang-uuid

**Comment by davidw** [comment]
Yes, that's right.  Same commit and everything, just that it's at github, because gitorious is closing its doors.

**Comment by drobakowski** [comment]
Oops, sorry I've missed this conversation... See #215

**Comment by danikp** [comment]
it's ok, PRs always welcome.
closing.
