### ISSUE TITLE
Is it possible to filter query results?

### ISSUE THREAD

**Issue by laxmikantG** [ErlyORM/boss_db#222]
I am using `boss_db` with `erlang` and `chicagoboss`. Right now, I'm making two separate queries for a result. Which I assume can be done in one query but don't know how. 

**Query1**

    ActiveUserList = boss_db:find(user,
                                 [{status, 'equals', active},{cid, 'equals', Cid}]).

**Query2**

    ActiveLegalUserList = boss_db:find(user, 
         [{status, 'equals', active},{cid, 'equals', Cid},{legal, 'equals', true}]).

Is there any way to achieve this in one query? 
like: 

    ActiveLegalUserList = ActiveUserList:filter({legal, 'equals', true}).

**Comment by danikp** [comment]
you can use lists:filter to filter query results

**Comment by davidw** [comment]
I just use SQL when queries are more complex - `find_by_sql` for instance.

**Comment by danikp** [comment]
@davidw, that not our case, cause you doing two queries anyway.

**Comment by laxmikantG** [comment]
@danikp @davidw  
Thanks for your suggestions. lists:filter worked for me. But still I would expect that as a feature. 
Thnk you
